
<h1><?php echo $categories_names[$category_id-1];?></h1>
<hr>

<nav aria-label="Page navigation">
  <ul class="pagination">
    <?php foreach ($pagination->buttons as $button) :?> 
        <li <?=$button->isActive ? '' : 'class="disabled"' ?> >
            <?php if ($button->isActive) : ?>

                <a href="/main?page=<?=$button->page?>&amp;category_id=<?=$category_id?>"><?=$button->text?></a>
            <?php else : ?>
                <span aria-hidden="true"><?=$button->text?></span>
            <?php endif ?>
        </li>
    <?php endforeach ?>  
  </ul>
</nav>


<div class="row" id='js-articles'>
    <div class="col-sm-6 col-md-4" style='display:none' id='js-article-item-tpl'>
        <div class="thumbnail book-item">

            <div class="caption">
                <img src="/img/" class="img-thumbnail" alt="">
                <h3></h3>
                <p></p>
                <p>
<!--                    <a href="/cart/add/" class="btn btn-default js-add-to-cart" role="button" data-id=''>Add to cart</a>-->
                    <a href="articles/?article_id=" class="btn btn-primary" role="button">Read this article</a>
                </p>
            </div>
        </div>
    </div>
  
    
    <?php foreach ($articles as $article) : ?>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail book-item">


            <?php if(file_exists(WEBROOT . 'img' .DS .$article->getImg() )){ ?>
                <img src="/img/<?=$article->getImg();?>" class="img-thumbnail" alt="">
            <?php } elseif(file_exists(WEBROOT . 'img' .DS .$article->getImg() )){ ?>
                <img src="/img/<?=$article->getImg();?>" class="img-thumbnail" alt="">
            <?php } else{?>
                <img src="/img/default.jpeg" class="img-thumbnail" alt="">
                <img src="/img/default.jpg" class="img-thumbnail" alt="">
            <?php } ?>


          <div class="caption">
            <h3><?=$article->getTitle();?></h3>

            <p>
                <a href="articles/?article_id=<?=$article->getId();?>&amp;category_id=<?=$category_id?>" class="btn btn-primary" role="button">Read this article</a>
            </p>
          </div>
        </div>
      </div>
    <?php endforeach ?>
    
</div>


<nav aria-label="Page navigation">
  <ul class="pagination">
    <?php foreach ($pagination->buttons as $button) :?> 
        <li <?=$button->isActive ? '' : 'class="disabled"' ?> >
            <?php if ($button->isActive) : ?>
                <a href="/main?page=<?=$button->page?>&amp;category_id=<?=$category_id?>"><?=$button->text?></a>
            <?php else : ?>
                <span aria-hidden="true"><?=$button->text?></span>
            <?php endif ?>
        </li>
    <?php endforeach ?>  
  </ul>
</nav>
<button type='button' class='btn btn-lg btn-primary' id='js-load-articles' data-offset='6' data-count='3' data-category_id='<?=$category_id?>' >Load more articles</button>



<script>
    $(document).ready(function() {

        var $loadBtn = $('#js-load-articles');
        var url = '/main-ajax?count=' + $loadBtn.data('count') +'&category_id='+$loadBtn.data('category_id') + '&offset=';

        // handlers for handling different response status codes
        function handleSuccess(response) {
            var articles = response.data;
            var key;
            var $articleItemTpl = $('#js-article-item-tpl');
            var $articles = $('#js-articles');
            var $caption, $link, linkHref;

            for (key in articles) {
                var article = articles[key];
                var $articleItem =  $articleItemTpl.clone();
                $caption = $articleItem.find('div.caption')
                $caption.find('h3').first().text(article.title);

                $link = $caption.find('a').first();
                linkHref = $link.attr('href');
                $link.attr('href', linkHref + article.id);
                $link.data('id', article.id);

                $articleItem.fadeIn();
                $articles.append($articleItem);

                $link = $caption.find('img').first();
                linkSrc = $link.attr('src');
                $link.attr('src', linkSrc + article.img);
            }



            var offset = parseInt($loadBtn.data('offset'));
            offset += parseInt($loadBtn.data('count'));
            $loadBtn.data('offset', offset);

            console.log('success', response);
        }

        function handleFail(res) {
            // todo
            // var msg = JSON.parse(res.responseText);
            // $messageBox.html('<b>Save failed! ' + msg.data + '</b>');
            console.log('fail');
        }

        $loadBtn.click(function() {
            var offset = $loadBtn.data('offset');

            $.ajax({
                type: 'GET',
                url: url + offset ,
                statusCode: {
                    200: handleSuccess,
                    404: handleFail,
                    500: handleFail
                }
            }).always(function() {
                // $spinner.hide();
                console.log('always');
            });
        });
    });


</script>







