<script src="jquery-1.7.1.min.js"></script>
<script>
    function selectChange(val) {
        //Set the value of action in action attribute of form element.
        //Submit the form
        $('#myForm').submit();
    }
</script>

<table class="table table-striped books-list-table" >
    <tr>
        <td>
            <div class="row">
                <h1>Chose article to edit:</h1>
                <form id="myForm" method='post'>
                    <select onChange=selectChange(this.value) class="form-control" name="article_title" value="">
                        <?php if($article->getTitle() !==''):?>
                            <option selected><?=$article->getTitle();?></option>
                        <?php endif;?>
                        <?php foreach ($all_articles as $selected_article):?>
                            <option><?=$selected_article->getTitle();?></option>
                        <?php endforeach;?>
                    </select>
                </form>

                <?php if($article->getTitle() || $article_id):?>

                    <h1>Edit article:</h1>
                    <form method='post'>
                        Article title

                        <input type="text" name="edited_article_title" value="<?=$article->getTitle();?>"  class="form-control"/>
                        <input type="hidden" name="article_id" value="<?=$article->getId();?>"/>
                        <br>
                        Article Text
                       <textarea style="overflow: scroll; min-height: 200px; "  name="article_text" value="<?=$article->getText();?>" class="form-control"><?=$article->getText();?> </textarea>
                        <br>

                        Category
                        <select class="form-control" name="article_category_id" value="">

                            <?php foreach ($categories_names_ids as $categories_names_id):?>
                                <?php if($current_article_category_name == $categories_names_id->getCategoryName()){?>
                                <option selected value="<?=$categories_names_id->getCategoryId()?>"><?=$categories_names_id->getCategoryName();?></option>
                                <?php }else{?>
                                <option value="<?=$categories_names_id->getCategoryId()?>"><?=$categories_names_id->getCategoryName();?></option>
                                <?php }?>

                            <?php endforeach;?>
                        </select>
                        <br>
                        tags (please use space between tags)
                        <input type="text" name="article_tags" value="<?=$article->getTags();?>" class="form-control"/>
                        <br>
                        <h4>The image (You can change the image and also upload a new one.)</h4>
                        <br>
                        <div style="max-height: 300px; overflow: scroll" >



                        </div>
                        <div style="max-height: 300px; overflow: scroll" >
                            <input style="border: 3px solid red" type = "image"  disabled value=""  src = "/img/<?=$article->getImg()?>" width="100px" height="65px"/>
                            <input  checked type="radio" name="img" value="<?=$article->getImg()?>" >
                            <?php foreach ($all_images as $image):?>

                                <?php if(file_exists(WEBROOT . 'img' .DS .$image) && $article->getImg() == $image) { ?>

                                <?php } else{?>
                                    <input type = "image"  disabled value=""  src = "/img/<?=$image?>" width="100px" height="65px"/>
                                    <input type="radio" name="img" value="<?=$image?>" >
                                <?php } ?>
                            <?php endforeach;?>


                        </div>
                        <br>
                        <br>
                        Article analytic text
                        <textarea name="article_analytics" value="" class="form-control" ><?=$article->getAnalytics();?></textarea>
                        <br>
                        <h3> <button type="submit">Save changes to article</button></h3>

                    </form>
                    <br>

                    </form>
                    <br>
                    <br>
                    <form method="post" enctype="multipart/form-data">
                        <h3>Upload new image to server </h3>
                        <input type="file" name="document" >
                        <button>Upload</button>
                    </form>
                <?php endif;?>
            </div>
        </td>
    </tr>

    </tbody>
</table>